### ISSUE TITLE
Ability to ignore host keys

### ISSUE THREAD

**Issue by ffainelli** [d-k-c/dsatest#1]
Hi,

I an issue with the handling of host keys, my device will re-generate a key every time it boots because that's really how it is set up at the moment.

If the host knows about this fingerprint, paramiko will throw an exception: 
`
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 366, in connect
    raise BadHostKeyException(hostname, server_key, our_server_key)
paramiko.ssh_exception.BadHostKeyException: ('192.168.3.17', <paramiko.rsakey.RSAKey object at 0x7fc16be9b518>, <paramiko.rsakey.RSAKey object at 0x7fc16bf0fcf8>)
`

So usually from there, you would remove the offending host fingerprint with ssh-keygen -f .. -R and then you would have your host no longer know about this fingerprint. It would be good if we had the option to ignore mis-matching host keys, or automatically (opt-in) replace them.

**Comment by ffainelli** [comment]
Looked at paramiko a bit last night and I am not sure this is something supported, or not in a straight forward way. We may have to manipulate the known_hosts file via paramiko though.

**Comment by d-k-c** [comment]
The issue is because SSHControl uses `load_system_host_keys()`. Skipping that step with the AutoAddPolicy allows to handle the issue you mentioned. I'm working on that right now.

**Comment by ffainelli** [comment]
Thanks!
