### ISSUE TITLE
Unstable parsing/hashing of links?

### ISSUE THREAD

**Issue by ffainelli** [d-k-c/dsatest#11]
Out of a few successful runs of the bridge test, I get either link0 or link1 to be used, which seems to indicate there may be some instability in how the links are parsed, this should only take a few successive runs to reproduce.

**Comment by d-k-c** [comment]
Indeed, `BenchParser` uses a dictionary to store links, but ordered is not garanteed. I'll replace that with an OrderedDict, that should make the parsing stable.
