### ISSUE TITLE
Add the ability to run in debug mode

### ISSUE THREAD

**Issue by ffainelli** [d-k-c/dsatest#3]
Hi,

Sometimes not all commands will work, so we need to be able to run in debug mode, having the ability to show which commands are being run (along with their actual arguments) on the host/board is helpful

**Comment by d-k-c** [comment]
Agreed, but using a simple `print` will mess with unittest output. I think using a [logger](https://docs.python.org/3/library/logging.html) would also us to print to `stderr` or to a file quite easily (let --debug take an argument, default to stderr if none specified). What do you think?

**Comment by ffainelli** [comment]
That seems to be a much better way to achieve that!
